import { TECH } from 'utils/tech';

import { CATEGORY } from './types';

export const CATEGORIES = Object.values(CATEGORY);

export const LANGUAGES = [
  TECH.CSHARP,
  TECH.CSS,
  TECH.GRAPHQL,
  TECH.HTML,
  TECH.JAVA,
  TECH.JAVASCRIPT,
  TECH.PYTHON,
  TECH.SOLIDITY,
  TECH.SWIFT,
  TECH.TYPESCRIPT,
];

export const FRAMEWORKS = [
  TECH.ANDROID,
  TECH.APOLLO,
  TECH.DOTNET,
  TECH.ETHERS,
  TECH.NEXTJS,
  TECH.REACT,
  TECH.REACT_NATIVE,
  TECH.RELAY,
];

export const DEVOPS = [
  TECH.AWS,
  TECH.AZURE,
  TECH.AZURE_FUNCTIONS,
  TECH.GITHUB_ACTIONS,
  TECH.DOCKER,
  TECH.KUBERNETES,
  TECH.TRAVIS_CI,
];

export const DATABASE = [TECH.MONGO, TECH.MYSQL, TECH.REDIS];
